### ISSUE TITLE
READ ME lacks documentation

### ISSUE THREAD

**Issue by ghost** [Naheel-Azawy/stpv#1]
How does one use this?

**Comment by Naheel-Azawy** [comment]
My bad! You're right, I should document it better, I'm just too busy and I forgot to do so.
I will add some additional details and perhaps screenshots too later today or maybe tomorrow.

Meanwhile you can install it and run stpv and/or stpvimg with no arguments and it will tell you how to use it. Also you can check fzfp as an example of how to use it with fzf. Or even better if you're not in hurry wait for me to write more details soon

**Comment by Naheel-Azawy** [comment]
I hope you're happy now!

**Comment by ghost** [comment]
Thank you. Unfortunately, I'm still unable to get this to work. Perhaps there are unmentioned dependencies?

Thanks again!
-- 
 Securely sent with Tutanota. Get your own encrypted, ad-free mailbox: 
 https://tutanota.com


Aug 10, 2019, 10:36 by notifications@github.com:

**Comment by Naheel-Azawy** [comment]
@eikaiwa-simons Any details? Error messages? System details?
