### ISSUE TITLE
Kitty support

### ISSUE THREAD

**Issue by Naheel-Azawy** [Naheel-Azawy/stpv#15]
Continue the discussion open by @Sqvid at #8 here

**Comment by Sqvid** [comment]
Perhaps a quick way to implement this would be `kitty +kitten icat`? (I'm still a programming newbie so I'm not too sure about my suggestions here)

According to `kitty +kitten icat --help` images can be scaled and placed at any x,y location. This should cut some labour.

**Comment by Naheel-Azawy** [comment]
Yeah that's right, I already did that [here](https://github.com/Naheel-Azawy/stpv/blob/master/stpvimg#L112). But I disabled it [there](https://github.com/Naheel-Azawy/stpv/blob/master/stpvimg#L39) for now because it's causing some mess when run inside a file manager

**Comment by Naheel-Azawy** [comment]
Hello @Sqvid, it has been a while.
I think kitty should work well for now. Please give it a try under wayland and let me know

**Comment by Naheel-Azawy** [comment]
I have just tested under GNOME in a wayland session and it seems to be working fine.
Will close this issue for now. Let me know if it doesn't work with you.
![Screenshot from 2022-03-06 12-55-32](https://user-images.githubusercontent.com/5764614/156918550-cc06f546-e45f-4617-9369-fb46eab4c3dd.png)
