### ISSUE TITLE
Mention what does the options in the configuration do in the README.md

### ISSUE THREAD

**Issue by yogeshdofficial** [Naheel-Azawy/stpv#16]
same as title

**Comment by Naheel-Azawy** [comment]
Sure. I'm working on cleaning the code and documenting it on the way.
I'll keep this open until I get it done

**Comment by Naheel-Azawy** [comment]
I hope you like it now.

**Comment by yogeshdofficial** [comment]
> I hope you like it now.

tnx It's more clear now and this project is very useful for someone like me who needs preview in lf in the easy way
