### ISSUE TITLE
Question: custom extensions

### ISSUE THREAD

**Issue by NikitaIvanovV** [Naheel-Azawy/stpv#21]
The README indicates that it's possible to define custom handlers but it doesn't mention the proper way to add them. Is it just editing the source code?

**Comment by Naheel-Azawy** [comment]
No you don't need to edit the source, unless you really want to. You can simply add your custom extension to ~/.config/stpv/config.sh.
An example of a cowsay handler is shown the the README [here](https://github.com/Naheel-Azawy/stpv#configuration).
This will show any file with a `.moo` extension in cowsay. You can also take any handler from the stpv source.
Maybe the README should include more details? Maybe it's time to write a man page?

**Comment by NikitaIvanovV** [comment]
I was confused because it was not obvious for me that you can include shell script code in `config.sh` (but now when I look at the `stpv` source code it makes sense because the config is simply sourced). I think README should clearly say that custom handlers must be added in `config.sh`.

> Maybe it's time to write a man page?

I'm not sure. It's not a usual utility program you use everyday on a command line and always need to have a quick access to a manual. In my opinion, in this case it's better to have all the documentation in the README.

**Comment by Naheel-Azawy** [comment]
I hope it's now clear enough on the README

**Comment by NikitaIvanovV** [comment]
It sure is! Thanks!
