### ISSUE TITLE
How can I use chafa as default previewer rather than kitty?

### ISSUE THREAD

**Issue by dragove** [Naheel-Azawy/stpv#30]
Hello I'm currently using `lf` as my file manager under wayland. `lf` leads me to this project for image preview. I've installed `kitty` but I mainly use `foot` as my default terminal emulator. I also installed `chafa` and it works in `foot`. I've added config to lfrc
```
set previewer stpv
set cleaner stpvimgclr
&stpvimg --listen $id
cmd on-quit $stpvimg --end $id
```
But this only works in kitty. How can I preview image in foot?

**Comment by Naheel-Azawy** [comment]
Hello,

I apologize for my extremely late response.
If you just want to use chafa you can add `PV_TYPE=text` to your config file (e.g. `~/.config/stpv/config.sh`).
Does that solves the problem for you?

As of actual images in foot in particular, I haven't used foot before. But it seems that it supports sixel which I'm interested in adding.
But to be honest I'm not too sure when can I get this done.

**Comment by dragove** [comment]
It only shows image info but not preview the image.
If I just type:
```bash
ID=$$
stpvimg --listen $ID &
stpvimg --add $ID myimg.png
```
it can preview image in foot terminal. Maybe I have something missing in lf config.
BTW, will you add `notcurses` support? `ncls` (a tool in notcurses) has better color in my terminal.

**Comment by GreenSleeper** [comment]
> It only shows image info but not preview the image. If I just type:
> 
> ```shell
> ID=$$
> stpvimg --listen $ID &
> stpvimg --add $ID myimg.png
> ```
> 
> it can preview image in foot terminal. Maybe I have something missing in lf config. BTW, will you add `notcurses` support? `ncls` (a tool in notcurses) has better color in my terminal.

Have you solved this? I'm facing the same problem.

**Comment by Naheel-Azawy** [comment]
Hello again,
I wanted to install foot and some wayland DE to try this. But it looks like I forgot to do so... Thanks @GreenAsFuck for the reminder.
Anyway, I just installed GNOME and tried it on foot. Looks like the issue was with `isalive()`. Should be fixed now.
Please let me know if chafa works fine with you now.
`notcurses`? Idk, I haven't tried this before will see

**Comment by Naheel-Azawy** [comment]
This `ncls` in `notcurses` doesn't look very nice (left). Am I doing it wrong?
![Screenshot from 2022-12-02 22-23-39](https://user-images.githubusercontent.com/5764614/205370870-cfe0b7a3-35c7-4567-9418-cc8e83c99861.png)

**Comment by dragove** [comment]
Maybe the output quality of `ncls` is depends on terminal emulator. I've tried it on `kitty`, `foot` and `wezterm`, they perfromed well.

**Comment by Naheel-Azawy** [comment]
Yeah indeed, `ncls` seems to be using different methods. For foot, it seems to be using sixel. This brings us back to #31.
`chafa` supports sixel already. I think something like `chafa -f sixel <you-img>` should work as good as `ncls`.
I have just updated stpv. Now you can set `PV_TYPE=sixel` in your config file and sixel should work. It should work in the sense that if you try `stpv <your-img>` the image should be displayed.

But this brings another problem to the table. These previewers are made to work inside things like `fzf` or `lf`. But from my experience, sixel doesn't work with either of these. There are open issues there
https://github.com/junegunn/fzf/issues/2544
https://github.com/gokcehan/lf/issues/675

**Comment by Naheel-Azawy** [comment]
There appears to be an interesting discussion on ctpv as well https://github.com/NikitaIvanovV/ctpv/issues/14
As @NikitaIvanovV suggested, [this fork of lf](https://github.com/horriblename/lf) should get the job done.
Still not sure what to do with fzf though.

**Comment by dragove** [comment]
Hello, sorry for bother you again. I've tried both chafa and sixel in foot with lf-sixel fork.
Firstly, I tried with config `PV_TYPE=chafa` and it fails to run with `stpvimg --add $ID 1.jpg` (immediately stop with exit code 1)
Then, I tried `PV_TYPE=sixel` and `stpvimg --add $ID 1.jpg` goes well, but it doesn't work on lf-sixel.
The good news is that `set autochafa` in `ctpv` works for me in `lf-sixel`.

BTW, I think `bc` should be listed in dependencies.

**Comment by Naheel-Azawy** [comment]
Yeah, `PV_TYPE=chafa` won't do any good. `PV_TYPE=sixel` is the right option.
Looking at [ctpv](https://github.com/NikitaIvanovV/ctpv/commit/08095635bc879115cfd47f48204817ab2868127a#diff-6a4f74d808859df622a0123332bee1da7b46c153c2604ef2a1d33a110b1a5ba0R69), I can see what's going on there. Just pushed a new commit. This should work with stpv now.

Here's a screenshot from `foot`:

![Screenshot from 2022-12-09 19-06-50](https://user-images.githubusercontent.com/5764614/206751380-d351967e-0feb-48fc-a28a-8883412c1761.png)

> The good news is that set autochafa in ctpv works for me in lf-sixel.

If you feel comfortable with ctpv that's great

> BTW, I think bc should be listed in dependencies.

Good point. I remember at some point in time I had a good reason to use it. But now I can't remember any of that.
Anyway, I think it's better to use `timeout` from coreutils anyway

**Comment by dragove** [comment]
Thanks for your  patient reply and update. previewer works now.
