### ISSUE TITLE
Sixels support on foot

### ISSUE THREAD

**Issue by cain-dev** [Naheel-Azawy/stpv#31]
Hi, first, thanks for your contribution, I was using your script with kitty but my computer is not the best and the slowness when opening kitty is noticeable, so I've been using foot terminal instead. I've tested ranger-sixels with foot terminal and it was very interesting, but due to the speed of the ranger itself when running on my machine I've been trying to migrate to lf.

I don't know how complex this is and I apologize if I'm talking nonsense or asking too much, but, if possible, I would like to have a lighter experience (using foot terminal view with cache directory) but with a little more quality (provided by sixels through chafa). 

Could you implement such function please?

**Comment by Naheel-Azawy** [comment]
Thank you for your interest. And I'm sorry for my super slow response.
Nope that's not nonsense. Sixel has been in the back of my mind for a while too.
And stpv is indeed slower than it should be. I think [ctpv](https://github.com/NikitaIvanovV/ctpv) has some potential once it gets ready.

Anyway, I'm still living in the X11 land. I haven't tried foot yet. But I'll take that out of my brain and add it to my todo list. But no promises to get it done very soon.

**Comment by Naheel-Azawy** [comment]
Based on the discussion in issue #30, sixels now should work on foot and others.
However, the file manager must support sixel as well (e.g. [lf-sixel](https://github.com/horriblename/lf))
