### ISSUE TITLE
after exiting  lf, image remains in the terminal

### ISSUE THREAD

**Issue by Akavvi** [Naheel-Azawy/stpv#32]
terminal - kitty

https://user-images.githubusercontent.com/72504099/170862655-faa54206-8d7b-40dc-8d8e-0693a3915919.mp4

**Comment by NikitaIvanovV** [comment]
Did you try adding this line to your lf config?

```
cmd on-quit $stpvimg --end $id
```

**Comment by Akavvi** [comment]
> Did you try adding this line to your lf config?
> 
> ```
> cmd on-quit $stpvimg --end $id
> ```

yes, i'm copied config from docs

**Comment by Naheel-Azawy** [comment]
I can confirm that this happens with kitty. It only happens with me if I close lf quickly while the image is previewed. Otherwise it functions normally.
I guess this might be because the icat clear is being sent before the image is completely shown? I'm not sure yet.

**Comment by NikitaIvanovV** [comment]
What if you call `icat --clear` in `end()` function when kitty is used?

**Comment by Akavvi** [comment]
> icat --clear

how i can do that?
